### ISSUE TITLE
Make mining less random.

### ISSUE THREAD

**Issue by Dioarya** [MinicraftPlus/minicraft-plus-revived#176]
Currently, if you try to mine an ore there is a chance for it to not damage the ore but reduce the durability of the pickaxe.
I think after 3 or some more misses there should be a guaranteed hit to make mining ores less infuriating and make the possibility to not be able to hit any ores forever (due to randomness) not a problem.

**Comment by Makkkkus** [comment]
The hits with low damage doesn't hurt your pickaxe, but is actually caused by a bug it seems.

**Comment by Dioarya** [comment]
> The hits with low damage shouldn't hurt your pickaxe, but is actually caused by a bug it seems.

But can you just like remove the randomness completely... pls

**Comment by Litorom** [comment]
I have also experienced this problem. It appears that the “pickaxe damage to a rock tile” for example uses it properly the first time but the second time uses “by hand damage to a rock tile” unless you wait about 3 seconds. If you wait 3 seconds before striking again it works properly.
