### ISSUE TITLE
end update idea

### ISSUE THREAD

**Issue by RandomTNT** [MinicraftPlus/minicraft-plus-revived#198]
Whoop my bad, Here's the idea: random generating strongholds (minecraft-a-like type) with no patterns whatsoever. End dimension + Dragon boss

**Comment by Makkkkus** [comment]
You need to add a description. Click on the three dots in the top right corner of the box with "No description provided", and add a description of your idea.

**Comment by Makkkkus** [comment]
We will not copy Minecraft on this, sorry.
