### ISSUE TITLE
Better status GUI

### ISSUE THREAD

**Issue by Makkkkus** [MinicraftPlus/minicraft-plus-revived#204]
**Is your feature request related to a problem? Please describe.**
Currently, the status gui is composed of a black box, and some icons. This looks dated, and is something we probably should fix.

**Describe the solution you'd like**
Create a new, better-looking status GUI. Also, adding a hot bar.

**Image of the gui**
![image](https://user-images.githubusercontent.com/37084190/134726367-68746591-d700-4181-ab49-c7824c0cf3b3.png)

**Comment by hilcon222** [comment]
I'm not familiar with github issues... lets'hope the hotbar will be added.

**Comment by TheBigEye** [comment]
I would recommend you to change the scale of the GUI to have more space (although that would affect the vision distance of the player, since the rendering logic is tied to that)

**Comment by BenCheung0422** [comment]
The rendering engine would be entirely changed, GUI would no longer be depending on the size. The size and rendering behaviours are separated between the world and HUD.

**Comment by Makkkkus** [comment]
Closing because this has been abused. The status gui is fine as is.
