### ISSUE TITLE
[FEATURE] More in-depth farming system

### ISSUE THREAD

**Issue by lino-levan** [MinicraftPlus/minicraft-plus-revived#230]
**Is your feature request related to a problem? Please describe.**
I feel like the farming system in the game is too basic and undervalued.

**Describe the solution you'd like**
1. In my opinion having an achievement tied to it in #202 could be a good idea. 
2. I think maybe adding something like a watering tin would be in the style of the game, built using gems (or maybe cloud ore when that gets added at some point). 
3. Some sort of furniture item to help farming (or maybe to obtain new food recipes or seeds)
4. Maybe different types of trees? This would be purely visual.
5. Different types of grass? This would also be purely visual.
6. Growable cactuses.
7. Make certain animals try to stomp and eat certain foods.
8. Add other growable plants / flowers?

Would love to discuss with @Makkkkus, @Litorom, and @TheBigEye on this.

This is nearly 100% not going to happen anytime soon.

**Comment by Litorom** [comment]
I agree on this, but I feel we would need to change I few things on this list.

**Comment by Makkkkus** [comment]
Might add a suggestion proposed on the Discord: Adding fertilizers like compost.
