### ISSUE TITLE
[BUG] At higher speed of movement, the hitbox of the mobs and that of the player behaves strange

### ISSUE THREAD

**Issue by TheBigEye** [MinicraftPlus/minicraft-plus-revived#246]
**Describe the bug**
By increasing the speed of an entity or player, the sprite is separated from the hitbox

**To Reproduce**
1. Drink a speed potion (or just increase the speed of the player)
2. Try to hit an enemy or a tile (you will notice that the player's sprite is further away from the hitbox, also and observe that the distance between the player's sprite and the tile increases, when trying to attack an enemy, most of the time it could fail the hit)

**Expected behavior**
The hitbox of the mobs (including the player) should be centered with the sprite

**Screenshots**
### Enemy hit:
![test](https://user-images.githubusercontent.com/63316583/147489592-86311413-e95f-48b5-8947-ade750fff073.gif)

### Tile distance, move speed = 2:
![dung](https://user-images.githubusercontent.com/63316583/147489867-bab76a93-49d1-4771-8e8f-e2e66007ed55.gif)

### Tile distance, move speed = 3 or more:
![dung](https://user-images.githubusercontent.com/63316583/147490410-914450d1-bd9a-4b0b-a886-4be61bef8489.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10, It is more likely to happen in other systems]
 - Version [all 2.0.1 - 2.0.7]

**Additional context**
Apparently the hitbox moves a lot to the right

**Comment by Makkkkus** [comment]
Moved to low-priority since this is not a game breaking bug.

**Comment by Litorom** [comment]
Now that I think about it while looking at Entity.java. I think the issue is how “x >> 4” works. I think at a higher movement number it messes up its calculations. Since it’s dividing it’s valve by 16 since tiles are 16x16.
