### ISSUE TITLE
[FEATURE] Allow Texture Packs to change names of items, tiles, etc.

### ISSUE THREAD

**Issue by Litorom** [MinicraftPlus/minicraft-plus-revived#249]
**Is your feature request related to a problem? Please describe.**

Poor flexibility with game customization.

**Describe the solution you'd like**

Allow texture packs to change text using locales. 
Using names of preexisting locales will replace them.
Ability to add locales that are not in code.
Reformat the folder structure of texture packs.
Texture pack may have to be renamed to something like Resource Packs (Similar to the issue Minecraft encountered).

**Comment by lino-levan** [comment]
It feels very likely that we package this update with #256 as well.

**Comment by lino-levan** [comment]
I am working on this actively, my branch now loads texture packs using the following format:
```
textures
    entities.png
    gui.png
    items.png
    tiles.png
sound
    bossdeath.wav
    ...
localization
    british_en-gb.json
    ...
```

I haven't implemented actually loading the localizations and sounds but once I do I'll do a pull request

**Comment by lino-levan** [comment]
Should we include books in this change in the "texture pack" system or not? Should we rename texture packs to resource packs or something similar?

**Comment by Litorom** [comment]
No don’t do books, that’s too complicated. Yes rename Texture Packs to something similar. Also if you could add support to the old format to default to textures would also be nice.

**Comment by lino-levan** [comment]
Okay, I'm going to go ahead and push a polish patch to my branch and do a pull request. Everything seems to be working but I haven't (and don't plan to) implemented sounds.

**Comment by Litorom** [comment]
Okie, I personally don’t care about the sounds at this time. Maybe we can add it later.

**Comment by lino-levan** [comment]
It is definitely easy to extend the current system to include basically any resource. I don't have any experience messing with the game's sound code so I don't want to get into that right now.
