### ISSUE TITLE
[BUG] When an object has a big light radius and the player moves away, the light radius behaves strangely.

### ISSUE THREAD

**Issue by TheBigEye** [MinicraftPlus/minicraft-plus-revived#253]
**Describe the bug**
**1** - If an object (such as a flashlight for example) has a very large light radius, when the player moves away, said light radius (still visible) stops rendering, most likely this is due to the game's rendering system.

**2** - If an object or entity has a radius of light that is too large, when moving away from said object: first, the dither is not rendered, and second, it changes the terrain from light to dark immediately when leaving the lighting radius

**Note:** this also happens with mobs and tiles (in short, everything that emits light)

**To Reproduce**
1. Place a gold lantern (or something that has a large illumination radius).
2. Get away from the object a bit.
3. You will notice that the light radius stops rendering immediately before moving completely away from the object.

**Expected behavior**
When moving away from the object or entity that emits the light radius and the light radius being 100% not visible, it should not render

**Screenshots**
![dung](https://user-images.githubusercontent.com/63316583/148803548-ea0b6635-cd7b-4611-bdee-87c2dcb7d868.gif)

**Desktop (please complete the following information):**
 - OS: Windows, Linux and more likely on MacOS
 - Version: 2.1.0-dev2 (also happens in previous versions)

**Additional context**
Apparently the game by not rendering the object (at some point) also stops rendering the light radius.

**Comment by lino-levan** [comment]
This occurs with every entity that is big enough. It just so happens that big lights trigger this behavior as well.

**Comment by Litorom** [comment]
I think this is caused from unloading that area, I think there is a loading radius where the player is and upon moving unloads.

**Comment by Domaman202** [comment]
for example, it is possible to not look for an object so that its light is seen in the player's render.

**Comment by TheBigEye** [comment]
So.. wont fix?, nah, i found the problem in the code

**Comment by lino-levan** [comment]
It's a bug yeah
