### ISSUE TITLE
Individual textures per sprite

### ISSUE THREAD

**Issue by AstroCat22** [MinicraftPlus/minicraft-plus-revived#257]
That's about it.

**Comment by lino-levan** [comment]
@Makkkkus thoughts?

**Comment by Makkkkus** [comment]
It could be a long-term goal, yes

**Comment by Makkkkus** [comment]
This probably won't happen. The current system is good enough for its use-case.

**Comment by Makkkkus** [comment]
Will not implement because it would add many unnecessary disk operations, and be confusing to work with. Parts are already implemented, though, such as with skins.
