### ISSUE TITLE
[FEATURE/BUG] Air Wizard Respawn

### ISSUE THREAD

**Issue by Litorom** [MinicraftPlus/minicraft-plus-revived#263]
**Is your feature request related to a problem? Please describe.**
Old Worlds that beat all Air Wizards cannot achieve their related Achievements.

**Describe the solution you'd like**
A form of Air Wizard Respawn, maybe finally add cloud ore to craft a summon item.

**Describe alternatives you've considered**
Item/tile ritual?

**Comment by TheBigEye** [comment]
Well, simply, when loading an old world, it detects if the AirWizard was defeated (or just detects if it's not within sky level), if true, then gives the player the achievement instead of respawning the AirWizard. On the contrary, if the AirWizard is detected, then the achievement is not given until it is defeated.

**Comment by TheBigEye** [comment]
In simple words, it is checked within the saved world (or the files) if the AirWizard entity is saved (usually when defeating it and saving the world, the entry of said entity disappears from the files)

**Comment by TheBigEye** [comment]
By the way, there is a function that respawns the AirWizard, rather it is a check in level.java
![image](https://user-images.githubusercontent.com/63316583/150643433-feebac51-b1b5-4b9b-a7bb-6af59e5ce332.png)

**Comment by Litorom** [comment]
This would have to be changed, as much as it’s a new feature, it’s a bug as old worlds can’t earn the related achievements. The player would have to make a new world to earn them if this isn’t done.

**Comment by TheBigEye** [comment]
did you see this? https://github.com/TheBigEye/minicraft-plus-revived/commit/ea80592b4094251a283808884ae0d335aa6b0e4bV
Although well... it's an example now ._.

**Comment by Litorom** [comment]
I see, that would work too. Although this feature would still be nice.

**Comment by TheBigEye** [comment]
> I see, that would work too. Although this feature would still be nice.

yeah, it sounds good

**Comment by Litorom** [comment]
Fixed by #265.
