### ISSUE TITLE
Maven for potential mod support using Fabric?

### ISSUE THREAD

**Issue by PseudoDistant** [MinicraftPlus/minicraft-plus-revived#266]
I've created a Fabric MinicraftGameProvider very recently, and I'm working on a dev environment and API for it. Is there a Maven that I can use to download Minicraft artifacts automatically, and if not, do you intend to make any?

**Comment by Makkkkus** [comment]
I'm not very familiar with maven publishing, but I can't imagine it being too hard.

**Comment by PseudoDistant** [comment]
Oh, also, some proof that I do have a working Minicraft Fabric environment:
![unknown](https://user-images.githubusercontent.com/67613281/151715492-3522fe3f-4735-405d-8bc0-bcad05d2f18e.png)
![unknown2](https://user-images.githubusercontent.com/67613281/151715495-b1877064-6642-4d6a-8f5e-053a0700218c.png)
![unknown3](https://user-images.githubusercontent.com/67613281/151715498-f97cbc5d-47ab-4104-b782-e8ed1e34e9ee.png)
https://github.com/MiniFabric

(It is currently based on the original, fetched from the Ludum Dare 22 repo, but could be immediately made to work with MinicraftPlus.)

**Comment by Makkkkus** [comment]
Holy shit, you just did this for us...

**Comment by Makkkkus** [comment]
I will add that I have no idea of how to publish anything to maven.

**Comment by PseudoDistant** [comment]
Once you set up a server, you can just add the publish config to Gradle, and Gradle will take care of it for you.

You'd just have to set up a publish action.
https://github.com/MiniFabric/MinicraftGameProvider/blob/master/.github/workflows/publish.yml

**Comment by PseudoDistant** [comment]
> Holy shit, you just did this for us...

I had no idea you wanted to set up mod support via Fabric, glad to see I helped. :>

**Comment by PseudoDistant** [comment]
If you want to discuss API development with us, we have a Discord server. :>

(Shameless plug)
https://discord.gg/MsQdqe52yT

**Comment by Makkkkus** [comment]
👍🏻

**Comment by lino-levan** [comment]
To clarify, you're using the fabric toolchain for this?

**Comment by PseudoDistant** [comment]
[fabricloader.log](https://github.com/MinicraftPlus/minicraft-plus-revived/files/7980776/fabricloader.log)

**Comment by PseudoDistant** [comment]
![Fabic](https://user-images.githubusercontent.com/67613281/152023760-86ec4cb5-bd7a-4999-b47b-cf40ae0312ab.png)

I was even assisted by both sfPlayer1, and modmuss50, on The Fabric Project's Discord.

**Comment by Litorom** [comment]
@PseudoDistant is this completed?
