### ISSUE TITLE
not letting me play mini craft and that’s the only reason I made an account

### ISSUE THREAD

**Issue by Rusty101223** [MinicraftPlus/minicraft-plus-revived#267]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 2.0.7]

**Additional context**

**Comment by Litorom** [comment]
Did you install Java?

**Comment by Litorom** [comment]
Closed due to inactivity
