### ISSUE TITLE
[FEATURE] Infinite Generation Opportunity 

### ISSUE THREAD

**Issue by Litorom** [MinicraftPlus/minicraft-plus-revived#272]
**Is your feature request related to a problem? Please describe.**

World are small and exploring is limited

**Describe the solution you'd like**

Add the ability for infinite generation using possibly [ChunX](https://github.com/bitbrain/chunx) chunk system.

**Describe alternatives you've considered**

Make our own chunk system.

**Additional context**

After such addition, can also add new structures to go with it.

**Comment by Makkkkus** [comment]
Duplicate of #317
