### ISSUE TITLE
[Feature] Have activated texture packs stay active after closing the application

### ISSUE THREAD

**Issue by JamesTDG** [MinicraftPlus/minicraft-plus-revived#278]
**Is your feature request related to a problem? Please describe.**
Texture packs at the moment have to be enabled manually every time the game is launched, which can get very annoying since packs can't be activated while in a world and that selecting a pack requires going out of the way to do so every time on startup

**Describe the solution you'd like**
Read the title

Another good fix would be allowing packs to be activatable while in a world.

**Comment by Litorom** [comment]
This won’t be done until resource packs are fixed. I suggest adding co-reliant tag.

**Comment by Makkkkus** [comment]
Resource packs are done

**Comment by Makkkkus** [comment]
Done
