### ISSUE TITLE
Screenshot tools

### ISSUE THREAD

**Issue by JamesTDG** [MinicraftPlus/minicraft-plus-revived#283]
**Describe the solution you'd like**
There should be an in-game tool to capture screenshots, something along the lines of using marker tools to mark the corners of a plane to gather this screenshot could be beneficial.

**Describe alternatives you've considered**
Optionally, there could instead be a button to take a screenshot of the current visible space (which would work better with my previous request), and a set of buttons to capture a screenshot of a 64x64 tile section of a world. Something like ctrl + s for just the screen and crtl + shift + s for the world would be easy to remember.

**Comment by Litorom** [comment]
Why not just use Win + Shift + S? (Windows)

**Comment by JamesTDG** [comment]
> Why not just use Win + Shift + S? (Windows)

This is because of a few reasons:
1. This tool is not available on every OS, especially on ones predating Win 10
2. Even with the tool, its next to impossible to get a pixel-perfect screenshot
3. The visual space of Minicraft is very limited compared to its cousin, so capturing screenshots of pixel art or mega bases is very limiting

**Comment by TheBigEye** [comment]
F2?, is universal

**Comment by JamesTDG** [comment]
> To clarify, there are two parts to this right (I'm not working on this, I just want to make sure I understand?
> 
> * Keyboard combination to take screenshot of screen (Essentially just Win + Shift + s)
> * Keyboard combination to take a screenshot of some subset of the world (probably 64 x 64 tiles around the player
> 
> Is that right?

Yes.
