### ISSUE TITLE
Books that are fished have error message

### ISSUE THREAD

**Issue by Comthefox2486** [MinicraftPlus/minicraft-plus-revived#285]
Whenever you fish a book and read it it says "This is an empty book, this should probably not happen"
![image](https://user-images.githubusercontent.com/61245294/156843012-8ae86f26-7381-4b48-8d7a-51a368e6b547.png)

**Comment by Litorom** [comment]
That’s intentional according to the code. It an empty book. @Comthefox2486 @Makkkkus

**Comment by Makkkkus** [comment]
Yes

**Comment by Comthefox2486** [comment]
Oh. alright.

**Comment by Makkkkus** [comment]
Still something we need to fix
