### ISSUE TITLE
Using JSON for data storage of Items and Tiles, also for save files on 2.1.0

### ISSUE THREAD

**Issue by BenCheung0422** [MinicraftPlus/minicraft-plus-revived#294]
**Is your feature request related to a problem? Please describe.**
Game Update Limitation

**Describe the solution you'd like**
The work is expected which consists of the all formatted files which are saved in the world save. Including `Entities.miniplussave`, `Game.miniplussave`, `Inventory.miniplussave`, `Level[0-5].miniplussave`, `Level[0-5]data.miniplussave` (will be renamed as `Level[0-5].miniplussavedata` temporally) and `Player.miniplussave`.

**Describe alternatives you've considered**

**Additional context**
Currently, I am working on the LevelData storing. I am deciding to work on Inventory and Level storages now.
Anymore working progresses will be shown here I guess.

**Comment by BenChueng0422** [comment]
Current progress: Done the works on LevelData (`Level[0-5].miniplussavedata`) storage. #284

**Comment by BenChueng0422** [comment]
Progress: Awaiting merge of #284 for confirmation and adjustment. Next awaiting task: Inventory. Currently working: Compatibilities of MiniMods Entity and Display/Menu.

**Comment by BenChueng0422** [comment]
Remove NBT (also SDT for the implementation). Use JSON instead.
