### ISSUE TITLE
[FEATURE] Support for long world names

### ISSUE THREAD

**Issue by TheBigEye** [MinicraftPlus/minicraft-plus-revived#297]
**Is your feature request related to a problem? Please describe.**
When someone creates a world and wants to give it a long name... most of the time the name goes off the screen.
![Very-long-name](https://user-images.githubusercontent.com/63316583/161163855-4cfeb962-88e0-478a-beaa-5895ac359007.gif)

**Describe the solution you'd like**
- So, when you type something long... the world name could be automatically centered on the screen while you type it and to avoid it going off the screen.

- Or, when the game detects that a letter has been entered, it would erase the label "Enter world name:", add the letters and center the text as you type, if all is erased and there is no letter, the label would be placed again.

**Comment by Litorom** [comment]
Why not have arrows and you can move back and forth using the arrow keys
