### ISSUE TITLE
Coal drops should only happen when hitting stone with a pickaxe

### ISSUE THREAD

**Issue by lino-levan** [MinicraftPlus/minicraft-plus-revived#298]
**Describe the bug**
In the code, and as well as everywhere else I look, coal is only intended to be dropped when a player breaks a stone tile with a pickaxe. This however, is not the case.

**To Reproduce**
1. Open any minicraft world
2. Break a stone tile with nothing but hands
3. See that it drops coal

**Expected behavior**
Expect stone tile to not drop coal if not broken with a pickaxe.

**Screenshots**
<img width="338" alt="Screen Shot 2022-04-05 at 9 58 00 AM" src="https://user-images.githubusercontent.com/11367844/161809232-34cf43f1-40e5-4340-9241-ae7f848d23b2.png">

**Comment by Litorom** [comment]
Why is this a bug?

**Comment by lino-levan** [comment]
This isn't intended behavior, at least according to the code. If this is intended behavior, then I'll do another pull request and clean up the StoneTile code because it's really poorly made otherwise.
