### ISSUE TITLE
A proper story

### ISSUE THREAD

**Issue by Makkkkus** [MinicraftPlus/minicraft-plus-revived#304]
**Is your feature request related to a problem? Please describe.**
The current game lacks a proper story line. We can use the air wizard as an example. We don't know nearly anything about it and how it came to be, why it attacks us, and we don't know why there are harmful mobs around us. Why are some mobs supernatural? These are all things we should fix.

**Describe the solution you'd like**
Create a story through for example quests, books in loot chests, or other things while playing the game.

**Additional context**
Quest system should be finished first.

**Comment by Litorom** [comment]
Should we make lore books?

**Comment by Makkkkus** [comment]
Yeah, this could be used

**Comment by BenCheung0422** [comment]
Some new structures containing lost pages (lore books)?

**Comment by Makkkkus** [comment]
You can put it in old structures.

**Comment by BenCheung0422** [comment]
Probably villages the best suit. I was wondering structures like lost structures (various types; also treasures).

**Comment by Makkkkus** [comment]
Also spawners. We could maybe add a new structure on the beaches. Sea related.

**Comment by Makkkkus** [comment]
This issue is in large part outdated now. This is no longer as important.

**Comment by BenCheung0422** [comment]
I do not agree. This is one of the important parts of this update.

**Comment by Makkkkus** [comment]
Don't reopen my own issues. You don't decide what I believe!
