### ISSUE TITLE
Stackable item limit and inventory limit

### ISSUE THREAD

**Issue by Makkkkus** [MinicraftPlus/minicraft-plus-revived#305]
**Is your feature request related to a problem? Please describe.**
Stackable items and inventories should have a limit to how many items they can contain. This should fix issues like #80.

**Describe the solution you'd like**
A cap on how many items we can put in a stack, and a cap on how many items we can put in our inventory.

**Comment by Litorom** [comment]
Just an FYI: This is partially implemented already and as been for a while but not active.

**Comment by Makkkkus** [comment]
Yes, this has been on the to-do list for a very long time. Also, it isn't partially implemented; it's not implemented at all. There is one variable in the StackableItem class. I would not call the partially implemented.
