### ISSUE TITLE
Review localization

### ISSUE THREAD

**Issue by Makkkkus** [MinicraftPlus/minicraft-plus-revived#306]
**Is your feature request related to a problem? Please describe.**
A lot of languages are missing localization. This makes the game unplayable in some languages, and this is especially bad for those who can't speak English that well.

**Describe the solution you'd like**
We should find translaters who can localize the missing entries, or remove the problematic files entirely.

**Additional context**
- [x] English
- [x] French
- [x] Hungarian
- [x] Indonesian
- [x] Italian
- [x] Norwegian
- [x] Portuguese
- [x] Spanish
- [x] Turkish

**Comment by Litorom** [comment]
Finished by PR #321

**Comment by Makkkkus** [comment]
They still haven't been reviewed yet, but it can be released
