### ISSUE TITLE
New GUI system

### ISSUE THREAD

**Issue by Makkkkus** [MinicraftPlus/minicraft-plus-revived#343]
**Is your feature request related to a problem? Please describe.**
The current GUI system isn't flexible enough for my liking. Currently you have many limitations when designing displays, and they don't really look good in general.

**Describe the solution you'd like**
Use the OpenGL backend to render a GUI on top of the game. The class based approach would replaced with a data-driven approach, where displays are defined in JSON files, or enum classes.

The current system of menus would be replaced with widgets, and more advanced functionality should also be implemented, like mouse movement.

**Additional context**
Reliant upon #318

**Comment by BenCheung0422** [comment]
With libGDX?

**Comment by Makkkkus** [comment]
I'm not familiar with libGDX, sadly.

**Comment by BenCheung0422** [comment]
Then LWJGL?

**Comment by Makkkkus** [comment]
Probably

**Comment by Makkkkus** [comment]
I have changed my mind on this. OpenGL/vulkan would be good for performance, and that can be done but the gui is good as is.

**Comment by Makkkkus** [comment]
Closing this because I edited #318 to reflect my current views.
