### ISSUE TITLE
Add signs

### ISSUE THREAD

**Issue by Litorom** [MinicraftPlus/minicraft-plus-revived#351]
**Is your feature request related to a problem? Please describe.**
We need signs to mark places, like your base or a farm.

**Describe the solution you'd like**
Add signs

**Additional context**
I’ll sign off on signs :p

**Comment by BenCheung0422** [comment]
Using signs for marking places?

**Comment by Litorom** [comment]
No, I mean to mark a place with a name. Like your base name, not on a map
