### ISSUE TITLE
Ability to select which monitor the game will run in

### ISSUE THREAD

**Issue by 1234567890-boop** [MinicraftPlus/minicraft-plus-revived#354]
**Is your feature request related to a problem? Please describe.**
I just wanted to play it on my main monitor instead of the secondary

**Describe the solution you'd like**
An option in the settings menu to select which monitor the game will run on would be very nice

**Comment by Litorom** [comment]
Can’t you move the window to your main monitor?

**Comment by Litorom** [comment]
Closing issue, old question assuming fixed.
