### ISSUE TITLE
game crash when loading save

### ISSUE THREAD

**Issue by FallinDown1** [MinicraftPlus/minicraft-plus-revived#361]
whenever i load a pre-existing world the game crashes when it gets to loading player
![image_2022-06-04_192624055](https://user-images.githubusercontent.com/106891001/172027372-f92db6bc-35a6-402f-9438-a564c75ec304.png)

**Comment by Makkkkus** [comment]
Compress the save file and send it here.

**Comment by FallinDown1** [comment]
Where is it located? just to be sure i dont send the wrong thing

**Comment by Makkkkus** [comment]
C:\Users\[UserName]\AppData\Roaming\playminicraft\mods\Minicraft_Plus\saves

**Comment by FallinDown1** [comment]
[wewewe.zip](https://github.com/MinicraftPlus/minicraft-plus-revived/files/8839054/wewewe.zip)

**Comment by Makkkkus** [comment]
Fixed

**Comment by FallinDown1** [comment]
cool, thanks
