### ISSUE TITLE
Mouse support for GUI

### ISSUE THREAD

**Issue by Makkkkus** [MinicraftPlus/minicraft-plus-revived#367]
**Is your feature request related to a problem? Please describe.**
It is quite annoying that we have the ability to design our games with mice in mind, but never do. This should lower the barrier to entry, and make the game seem more professional, which is something that is much needed.

**Describe the solution you'd like**
We should remake the GUI's, and maybe some of the game itself, to make it pointer-friendly.

**Comment by TheBigEye** [comment]
This does not go against the style and design philosophy of minicraft?

**Comment by Makkkkus** [comment]
Doesn't have to. Take a look at how OpenTTD does its menus.

**Comment by BenCheung0422** [comment]
Like the inventory with Minecraft look?

**Comment by BenCheung0422** [comment]
If mobiles are supported, this is supported.

**Comment by ThatBlockyPenguin** [comment]
I agree, as a new player, not using the mouse is a very unnatural experience.

**Comment by Makkkkus** [comment]
I'm sorry, we have already decided not to do this, but we might make it possible to use the mose for some minor actions.

**Comment by ThatBlockyPenguin** [comment]
Alright, no worries. I thought it was still under consideration due to the issue still being open.

**Comment by Litorom** [comment]
Good point, I’ll close it. If it comes up at a later date then it will be reopened.

**Comment by BenCheung0422** [comment]
Well, actually, mouse support would be implemented at the same time when mobile touching support is supported. Also, keyboard-exclusive games exist only in classic but not modern games, although that would mean that Minicraft+ might have to be reworked.

**Comment by BenCheung0422** [comment]
It should not be closed as completed. As might also do full cross-platform support, which means mobiles will also be implemented.

**Comment by Makkkkus** [comment]
Closing this again. This has nothing to do with mobile support.
