### ISSUE TITLE
Features Required to fit 2.2.0

### ISSUE THREAD

**Issue by Litorom** [MinicraftPlus/minicraft-plus-revived#369]
List of features that are required be implemented to match the theme of the update:

- [x] Storyline rewrite
- [x] New second boss to replace the removed one (#376)
- [x] Quests (#203)
- [x] Story elements to which the devs are fit:
- [x] Fences
- [x] Signs
- [x] Add a new structure to caves layers (likely delayed to 2.2.1+ or 2.3)
- [x] New Achievements
- [x] Audio Fixes

Suggested Features from the discord:  
- [x] Add OBK lore book (not necessary anymore)

**Comment by BenCheung0422** [comment]
#319 is moved to 3.0 update.

**Comment by BenCheung0422** [comment]
Possibly check if the items here are met.
