### ISSUE TITLE
Quests and crafting

### ISSUE THREAD

**Issue by NorthernL1ghts** [MinicraftPlus/minicraft-plus-revived#378]
When completing the challenge or quest -> Craft a sword, I receive an error that the tile item can not be casted. 

I have tried to download the code and execute this program in both InteliJ and Eclipse and get this error. 
![image](https://user-images.githubusercontent.com/34502005/177011112-d94be43f-873a-4489-987a-cfd221337e3f.png)
![image](https://user-images.githubusercontent.com/34502005/177011120-8fb76802-89ed-49e3-b1da-78a5ce1ffa20.png)

**Comment by Litorom** [comment]
Why are you looking for bugs in pre-dev code? This is invalid since quests are not finished and not close to finish. Also this is not a dev release, we only will accept dev release issues.
