### ISSUE TITLE
Complete cross-platform support

### ISSUE THREAD

**Issue by BenCheung0422** [MinicraftPlus/minicraft-plus-revived#388]
**Is your feature request related to a problem? Please describe.**
Like the Bedrock version of Minecraft, cross-platform version support mobile phone OSs (Android, iOS), consoles (Switch, Playstation), desktops (Windows, iOS). Many people have phones and phones are portable.

**Describe the solution you'd like**
As another version of Minicraft+, it must also be supported as the support of the Java version. The engine would be written in C++. We can then transmit the engine into various platforms.

**Comment by Litorom** [comment]
We can’t do consoles, for the main reason of that it’s not marketable. Consoles such as Switch won’t accept it.

**Comment by BenCheung0422** [comment]
Then we might exclude consoles if necessary.

**Comment by Makkkkus** [comment]
I support this, but I will not stand for a rewrite of the game in C++. We can make this project cross-platform instead. I'm also getting tired of the wannabe Mojang ethos; we don't have the resource to create a new game.

**Comment by BenCheung0422** [comment]
Not all platforms support Java, but all platforms support C++. That's why rewriting in C++ would be a better idea.

**Comment by Makkkkus** [comment]
Almost every platform supports Java; your statement is simply not true. We don't have the resources to rewrite the game in C++.

**Comment by BenCheung0422** [comment]
Really? https://stackoverflow.com/questions/1193524/can-we-run-java-applications-on-iphone, using C++ is a more compatible way.

**Comment by Makkkkus** [comment]
Java can cross-compile to cpp; cpp can not.

**Comment by BenCheung0422** [comment]
C++ is wider than Java. We could.

**Comment by BenCheung0422** [comment]
Also, the aim and the target of using and rewriting C++ as its base language is to let the game run smoothly natively.

**Comment by BenCheung0422** [comment]
As many people agreed that rewriting the game in C++ is redundant and not really beneficial. It is not planned, cross-platform support will be handled as well as in Java version.

**Comment by BenCheung0422** [comment]
Currently, this version is not supporting mobiles and/or consoles (if the problem on marketability can be resolved). If it is not possible to achieve it in Java only, the C++ version might possibly start developing.

**Comment by Makkkkus** [comment]
Don't have this discussion here.
