### ISSUE TITLE
Please consider making glass flasks reusable

### ISSUE THREAD

**Issue by Linsene** [MinicraftPlus/minicraft-plus-revived#422]
**Is your feature request related to a problem? Please describe.**

It feels almost like a bad joke when I find that the glass flasks are consumed when using potions, it's like the character eats up the whole thing. It kind of matters to playing experience since sand does not regenerate.  Also, old clothes disappear when new ones are put on, similar problem.

**Describe the solution you'd like**

Add in the Recipe "Glass to Glass Flasks" to the Workbench, and change the Recipes in the Enchanter to be "Glass Flask & Material to Potion", and then when using potion let the flask remain. As for clothes, it would feel great if the previous ones simply appear in the inventory when new ones are put on.

**Additional context**
I'm not native English speaker, please forgive for possible grammar mistakes.

**Comment by Linsene** [comment]
thinking again, maybe flasks should be directly produced from furnaces, i dont know...

**Comment by Litorom** [comment]
I like it.
