### ISSUE TITLE
Program crashes when deleting the world at the second time

### ISSUE THREAD

**Issue by LaJv2K** [MinicraftPlus/minicraft-plus-revived#434]
**To Reproduce**
1. Make sure there is no world in the game
2. Create a world
3. Save the world and exit
4. Enter to confirm deleting the world
5. Return from the world generation option to the confirmation message and enter to confirm deleting again

**Expected behavior**
Program crashes

**Screenshots**
![Screenshot 2023-02-03 112202](https://user-images.githubusercontent.com/48635800/216504936-5901c9c8-a2e5-4de2-87ec-dfda47027f8d.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version: [22H2]
 - OS build: [19045.2486]

**Comment by BenCheung0422** [comment]
Please provide the version of the game.

**Comment by LaJv2K** [comment]
> Please provide the version of the game.

2.1.3

**Comment by BenCheung0422** [comment]
I do not understand the step 5.

**Comment by BenCheung0422** [comment]
Alright, the version should be the pre-releases of 2.2.0 instead of 2.1.3, this only happens in the versions.
