### ISSUE TITLE
Hot bar HUD

### ISSUE THREAD

**Issue by hilcon222** [MinicraftPlus/minicraft-plus-revived#438]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I am using my pickaxe in the Underworld and mobs attack me. Then, I need to enter the inventory, equip a sword and fight them.

**Describe the solution you'd like**
I'd like to have an hotbar, like Minecraft's.

**Describe alternatives you've considered**
You could add one keystroke for using the pickaxe AND one keystroke for using a sword.

**Comment by BenCheung0422** [comment]
This functionality depends on the GUI/rendering engine. The size and appearance are quite limited. Dependant of #343 and #204

**Comment by Makkkkus** [comment]
Copy of #204
