### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by CodingPro1234** [MinicraftPlus/minicraft-plus-revived#479]
when i tried to delete my world, it crashed, and i dont know why. i havent messed with the game files. i only have
the jar. my error:  

![Capture](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/4bba8201-ad06-4805-be48-32e34bfa76fa)

i also downloaded the source code because i wanted to tweak the code a bit for fun, 
but it crashed... again. i havent messed with anything because it is fresh and that would be
stupid. my errors:     

![Capture1](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/6cb71b2b-7a7e-43aa-acb0-f0be2bd680e7)

![Capture2](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/d6844dcc-9c8a-453a-8f93-9a12c9d88e77)

edit: i also tried this multiple times in intellij idea. still not working. also, the error with deleting the world
is continuous. how i do it: i exit the world without saving (because i want to delete it), i click "load world" i shift d
the world. it brings me to new world, i exit, i see the prompt. press enter.... crash. please help. videos:   

https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/898772af-28a9-41de-aa8b-45d36e7bbba0

https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/d1747750-2f10-4b03-9f21-df9d147ed176

im not an expert at java. but i think its because you have `@Nullable` in there. but im probably wrong lol

error: `java.lang.NullPointerException` fix could be using a `try-catch` block or an `if-else` condition to check if a reference variable is null before dereferencing it.

(i pressed enter right before the crash)

**Comment by Litorom** [comment]
This bug was fixed in #436, the fix will be in dev4

**Comment by BenCheung0422** [comment]
As mentioned above, it has already been fixed, so this is a duplication of #434
For the crash on game startup, it has already been fixed by #456.
