### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by DevelopmentPenguin** [MinicraftPlus/minicraft-plus-revived#480]
You guys should add multiplayer because its more fun when you have
your friends playing with you. I find it better that way and less boring.

**Comment by Litorom** [comment]
Multiplayer was removed due to its buggy mess but it’s under development for better implementation.

**Comment by BenCheung0422** [comment]
Duplication of #270

**Comment by CodingPro1234** [comment]
oh ok thanks
