### ISSUE TITLE
death in top left

### ISSUE THREAD

**Issue by CodingPro1234** [MinicraftPlus/minicraft-plus-revived#483]
when i die in survival mode in latest version (dev3)
the death screen shows up in the corner. im prretty
sure it should be in the center.   picture: 

![Capture](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/76c2ee89-2e53-47fd-a709-65f83df4756d)

and im pretty sure this happens with all menus'

**Comment by BenCheung0422** [comment]
If you are talking about the relative position of the menus to the canvas, some menus are not set to be centered.

**Comment by CodingPro1234** [comment]
okay thanks, just checking.
