### ISSUE TITLE
inventory strip change

### ISSUE THREAD

**Issue by CodingPro1234** [MinicraftPlus/minicraft-plus-revived#485]
can you make it so the inventory black strip at the bottom in survival is like the one in real minecraft. seperated in squares. like this one for example:   

![Captur22e](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/59604520-b903-45de-b9f3-d38bbd235ee9)

**Comment by Makkkkus** [comment]
No. We're not going to do this.
