### ISSUE TITLE
jsmooth or convert to exe

### ISSUE THREAD

**Issue by CodingPro1234** [MinicraftPlus/minicraft-plus-revived#487]
is there a possibility you could use jsmooth with your jar files.
because jsmooth lets you make exe files with them and add an icon.
of course you can still have the jar file and you might be thinking "thats stupid. if you have an executable jar file and an exe that both do the same thing then theres no point." but i am just suggesting it for windows users. and plus, linux users can also run it on wine. so yeah. but you are probably not going to add it.

**Comment by BenCheung0422** [comment]
We are planning to make a game launcher for Minicraft+ in the future, so we will not convert those jar executable files into .exe file.
