### ISSUE TITLE
add full width

### ISSUE THREAD

**Issue by DevelopmentPenguin** [MinicraftPlus/minicraft-plus-revived#490]
is there  a possibility you could add full width whenever you go fullscreen. it would look a bit nicer when it is
full width and you can see the whole thing

**Comment by BenCheung0422** [comment]
This is a duplication of #277. There was a resolution about the aspect ratio, but encountered into an implementation failure. So, we are not going to support this until we have rewritten the rendering engine.

**Comment by CodingPro1234** [comment]
okay thanks
