### ISSUE TITLE
Changing the language makes all the texts completely lose

### ISSUE THREAD

**Issue by Holl0** [MinicraftPlus/minicraft-plus-revived#550]
I tried with multiple languages and it seems that the problem continues to be there. If some languages are missing I would recommend it directly to remove them.

https://github.com/MinicraftPlus/minicraft-plus-revived/assets/116159679/c13ba86f-536e-4db5-a4cf-7c5fad12273f

**Comment by BenCheung0422** [comment]
In the latest pre-release version of Minicraft+, only the English language has the most complete localization as the updated localizations are not imported yet, but there are some languages completed translations, so they will be imported by the next pre-release.
