### ISSUE TITLE
Sleep freezes the game

### ISSUE THREAD

**Issue by Holl0** [MinicraftPlus/minicraft-plus-revived#551]
Sleeping (in my case) makes the game freeze completely, but I discovered that by alternating the desktop and the game page at the same time I can solve the problem

https://github.com/MinicraftPlus/minicraft-plus-revived/assets/116159679/f1242ab8-333d-4412-8a07-69a219a167cf

**Comment by BenCheung0422** [comment]
Please describe your runtime environment, including Java version, OS, etc.

**Comment by Holl0** [comment]
> Please describe your runtime environment, including Java version, OS, etc.

Of course (I'm not expert so if I missed information do not hesitate to ask me)

OS: Windows 11 Home

Runtime enviroment:
![Immagine 2023-08-04 111727](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/116159679/d836c41d-63ee-4337-85ae-e672f87ea4d1)


Java Version:
![Immagine 2023-08-04 112633](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/116159679/eae35035-0b09-420b-84fb-d0cd05a92b0d)

**Comment by BenCheung0422** [comment]
Does the rendering freeze at other time? Does the game restore the player from the bed without alternating the game window focus? Does the time flow normally when the debug info is shown?

**Comment by Holl0** [comment]
> Does the rendering freeze of darkness at other time? Does the game restore the player from the bed without alternating the game window focus? Does the time flow normally when the debug info is shown?

_Question 1_: 
The game freezes but without making a black screen, it's more like the fps drops to 0 (I had previously played at Minicraft a long time ago but this problem as I remember wasn't there)

_Question 2:_ 
No, I tried leaving the game 5 minutes without alternating the game window focus but it stays frozen forever

_Question 3:_
No, I made a screen recorder with f3 just in case so that you can see that all the parameters freeze (even the day ticks)


https://github.com/MinicraftPlus/minicraft-plus-revived/assets/116159679/0d9c9c79-55ec-4e62-915b-a0d1ae62de87

**Comment by BenCheung0422** [comment]
It seems like your game is lagging at that time period.

**Comment by Holl0** [comment]
Can it be solved?

**Comment by Holl0** [comment]
> It seems like your game is lagging at that time period.

Can it be solved?

**Comment by BenCheung0422** [comment]
I am not sure if it can be fixed as it might be quite specific. A deep search would be required.

**Comment by Holl0** [comment]
> I am not sure if it can be fixed as it might be quite specific. A deep search would be required.

Okay I understand that I am the one who has bad luck 😓. 

If it helps to understand the problem by doing other tests I found that leaving the game frozen the long as the night lasts and alternating the game window focus only once actually it's as if the time passed, however the fps remained stuck but at least I only have to do this step once.

For the rest I hope this problem sooner or later will be solved and I wish the best for the future of Minecraft+, I love this game and the project and I think it has a lot of potential👍

**Comment by TheBigEye** [comment]
**My theory:** It seems that when the player goes to sleep, the TPS goes too high, which causes several game's events to happen in less than a second, which may be hanging the game thread with many tick updates, (If you’ve noticed, when the player sleeps in the bed, the passage of time in the game speeds up until dawn instead of instantly becoming day)

**Comment by BenCheung0422** [comment]
I think this kind of mechanism still needs to be improved. I may try to rewrite this mechanism to see if this problem can be solved. The current code is obviously not well-coded.

**Comment by BenCheung0422** [comment]
@Holl0 If this problem only exists in your world, can you upload the world so that we can troubleshoot and debug for you?

**Comment by Holl0** [comment]
here you go
[holl's world.zip](https://github.com/MinicraftPlus/minicraft-plus-revived/files/13890370/holl.s.world.zip)

**Comment by BenCheung0422** [comment]
Thank you for your assistance. The bug fix should be applied soon.

**Comment by Holl0** [comment]
Np I'm glad to have contributed
