### ISSUE TITLE
Constant crashes while fishing.

### ISSUE THREAD

**Issue by MaxiP17** [MinicraftPlus/minicraft-plus-revived#582]
**Sometimes when fishing, the game crashes. A lot. Could it be something that you pull?**

This is my first playthrough and i love the game; i've already played it for hours straight. After a long while, i noticed i haven't tried fishing yet, so i made myself a Gold Fishing Rod and went to the nearest big pool of water i had.
After like 15 catches, my game crashed.

_It has happened 4 times in less than 30 minutes, and it was as easy to replicate (so i could record it this time) as just fishing for maybe no more than three minutes._
I lost about an hour of progress the first time it happened, but saved after every few catches afterwards as to not lose my progress again.
[Gotta say, fishing is broken]

_In the video, i appear pressing the attack button as it happens, but it still happens the same way even if you stand still or fish from a different angle.
I also put the crash report in the video:_
https://github.com/MinicraftPlus/minicraft-plus-revived/assets/150219913/7375e4f2-8dfc-4c20-98cb-8a2ad2efc6c5

 - OS: Windows 10
 - Game version: "2.2.0-Dev3"

Anyways, good game, i absolutely had to play it when i found out about it online searching for the original. Thank you so much for it and hope it keeps going! I haven't found any other bugs myself aside of this one.

**Comment by BenCheung0422** [comment]
This should have been fixed by #534.
