### ISSUE TITLE
Canvas Initialization Failure

### ISSUE THREAD

**Issue by Yoon0117** [MinicraftPlus/minicraft-plus-revived#591]
**Describe the bug**
<img width="821" alt="Screenshot 2023-12-15 at 21 46 30" src="https://github.com/MinicraftPlus/minicraft-plus-revived/assets/90393596/07c1ebcd-f31f-4a69-b22f-97ec04e40136">

**To Reproduce**
Just opening the application

**Expected behavior**
Error comes up

**Desktop (please complete the following information):**
 - OS: Mac Sonoma
 - Game version: 2.2.0 dev 3

**Additional context**
I know this happened before and I checked the other issue posts, you guys have been saying duplicates of issue 460 or smth. But I can't find any SOLUTIONS for this, although in the comments one of the devs said this is fixed. The Nightly version in actions is expired so I can't get it anymore... Heres my java -version
<img width="455" alt="Screenshot 2023-12-15 at 21 49 39" src="https://github.com/MinicraftPlus/minicraft-plus-revived/assets/90393596/aafe070f-52fb-4dfb-ac12-69ac2b9f238e">

**Comment by Litorom** [comment]
I don't know where it says expired but the link is here: https://github.com/MinicraftPlus/minicraft-plus-revived/suites/19065643530/artifacts/1116275885

This is the latest nighty build, jar file is in "build/libs"

**Comment by Yoon0117** [comment]
Thanks.
