### ISSUE TITLE
mysterious ghost tiles that hurt the player

### ISSUE THREAD

**Issue by Beelzebold** [MinicraftPlus/minicraft-plus-revived#615]
**Describe the bug**
sometimes when walking around you may find a tile that when you try to walk into it, it'll deal one damage to the player and knock them back. can place walls on them but that won't remove them.

**To Reproduce**
idk what to suggest besides walking around. I don't remember a whole lot about my last time playing but I recall spikes in the sky layer, perhaps those are causing the issue? aside from that I have no clue how you could try reproducing it.

**Expected behavior**
to like, not run into ghost cacti or what. really sucks cos I found one right where I made the entrance to my little cave base and had to block it off and build/dig around it.

**Screenshots**
I have better than that, here.

https://github.com/MinicraftPlus/minicraft-plus-revived/assets/97068135/efa9a3fa-fb63-48b8-91de-6107577b33c3

**Desktop:**

- OS: win10
- Game version 2.2.0 pre5

**Additional context**
nope, got nothin else.

**Comment by Litorom** [comment]
Appears to be an invisible cactus. I’ll have someone look into it.

**Comment by Beelzebold** [comment]
> Appears to be an invisible cactus, especially with the sand particles. I’ll have someone look into it.

ah, so that was what those particles are. the other place I found one also had them. very curious though, I can't even imagine what quirk of world gen or storage could cause that. thanks for quick reply, btw.

**Comment by Litorom** [comment]
Okay, should be fixed via #601. I’ll probably post another dev release soon, so when that happens. Either test it and get back to me or send me your world file.
