### ISSUE TITLE
Enhanced spatial audio support

### ISSUE THREAD

**Issue by BenCheung0422** [MinicraftPlus/minicraft-plus-revived#624]
**Is your feature request related to a problem? Please describe.**
Our sound system can be enhanced and made more flexible and efficient. In addition, different kind of audio quality features can be added, in terms of Quality-of-Life.

**Describe the solution you'd like**
For the library, we may use OpenAL in place of native Java AudioSystem, then we can have more in-depth compatibility supports and advanced audio behaviors.
For the in-world behavior, the audio effects can be played reflecting the distance and even the direction (with respect to the top-down south-north player's view), by the volume and direction, dynamically.
Furthermore, we may even try to have 2/4/5/7 channel support as for the positional audio support, or even 2.1/4.1/5.1/7.1 sound source supports.

**Comment by Makkkkus** [comment]
I advice against; speaking from experience, positional sounds in a 2D game sound very uneasy. Also the player changes direction instantly, which would also be uncomfortable for the listener. So I advice as much as I can against using positional audio.

**Comment by BenCheung0422** [comment]
So in this aspect, I suggest 2 methods, one is related to the direction of the player, the another one is related to the relative position regardless the direction of the player pointing to.

**Comment by Litorom** [comment]
Okay, honestly please stop trying to fix things that aren't broken. We will be adding background music and ogg support eventually.

**Comment by BenCheung0422** [comment]
I rewrote the description for the topic.

**Comment by BenCheung0422** [comment]
This is superseded by #725.
