### ISSUE TITLE
Crafting menu and Inventory open at the same time

### ISSUE THREAD

**Issue by GameJarne** [MinicraftPlus/minicraft-plus-revived#627]
**Describe the bug**
When pressing SHIFT-E to open the crafting menu, the inventory also opens at the same time.

**To Reproduce**

1. Open any world
2. Press SHIFT-E

**Expected behavior**
Only the crafting menu should open.

**Screenshots**
![image](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/69422663/218c2464-23c8-48b7-8ca0-3f8b15ad0349)

**Desktop (please complete the following information):**

- OS: Windows 11
- Game version: 2.2.0 Pre-Release 5

**Comment by Litorom** [comment]
Cool, lovely....

@BenCheung0422
