### ISSUE TITLE
FPS dropping near lava

### ISSUE THREAD

**Issue by Tokarif** [MinicraftPlus/minicraft-plus-revived#672]
**Describe the bug**
When I approach lava my FPS are dropping drastically until game is almost unplayable.

**To Reproduce**

1. Go to a lava lake
2. See fps dropping

**Expected behavior**
Lava should behave like water... or any other tile. :-)

**Screenshots**

Lava level on the border of the map 42 FPS
![Capture d'écran 2024-05-01 011305](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/13903551/e112a23a-02c9-4be3-aebb-f880e55736bc)

Same world, same level, but in the middle of the lava lake : 5 FPS
![Capture d'écran 2024-05-01 011343](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/13903551/5949fe0c-3f32-4851-bd28-b5dbe45ec58a)

**Desktop (please complete the following information):**

- OS: Windows 11
- Game version 2.2.0-dev7
EDIT : Same issue with version 2.2.0

**Additional context**
The problem ocurs on all of my worlds.

**Comment by Litorom** [comment]
It would appear that this bug was fixed for Water tiles but someone forgot to fix Lava tiles too

**Comment by BenCheung0422** [comment]
After my testing, I spotted out that the issue is related to light rendering.

**Comment by BenCheung0422** [comment]
The number of lighting circles can go over 700, so it is a quite tricky issue to resolve.
