### ISSUE TITLE
setting a corner texture for grass (and likely other tiles) with a resource pack doesn't work

### ISSUE THREAD

**Issue by greenbean765** [MinicraftPlus/minicraft-plus-revived#700]
Some tiles (like grass) cannot have an inner corner texture added through a resource pack

**To Reproduce**: create a resource pack and add an inner corner texture for the grass tile by adding an appropriate image, and then adding this element ↓ to grass.png.json:

> "border": {

> > "corner": "file_name"

> }

The inner corner texture will not show up in game, grass will be drawn as though there were no inner corner texture

(the corner texture I made is a 16x16, 24-bit png)

**Expected behavior**
Tiles like rock have textures for convex corners, and the documentation for resource packs on the wiki describes the functionality as though it should apply to all tiles.

**Screenshots**
note the very ugly looking corners around the dirt patch
![beroken](https://github.com/user-attachments/assets/79a5ed9a-9073-4efb-bef2-2278ee9b6f49)

the same screenshot with corner textures superimposed (approximation of expected behavior)
![expected](https://github.com/user-attachments/assets/67e0cbd0-7191-457d-8891-383c6b3f9df5)

and then heres screenshots of the files, and the contents of grass.png.json:
![files](https://github.com/user-attachments/assets/1bc35126-3602-4b9e-ac3f-45241c4a54b7)
![json contents](https://github.com/user-attachments/assets/c890ca37-5071-4d8e-b84b-5488414f42e5)

- OS: Windows 10
- Game version: 2.2.1-dev1

**Comment by BenCheung0422** [comment]
In the current texture system, corners do not work without borders. Is it the case you are facing? If so, it is expected.

**Comment by greenbean765** [comment]
I do have borders set, as seen in the screenshot. Despite this, the corners don't show up.

**Comment by BenCheung0422** [comment]
Okay, I have checked and debugged deeply. Grass tile was set to not to render with diagonal tiles hardcodedly (thus corners tiles are not detected), and that was set versions before.

**Comment by BenCheung0422** [comment]
This config is set for both sand and grass tiles. When it is set, corners are always rendered as "full" regardless of setting of corner texture, and while it is set as "singleton', "border center" is never rendered.

**Comment by Litorom** [comment]
Should this be made so it can be customizable via resourcepacks?

**Comment by BenCheung0422** [comment]
This can be complex, but some parts might be, still, as of the complexity, it would be put into the development of rewriting stage in 2.3.

**Comment by BenCheung0422** [comment]
However, at the moment, I need to confirm whether we need `!side` in the code for both sand and grass tiles.

**Comment by BenCheung0422** [comment]
The effects when there are tiles exist on orthogonal directions (for each pair of orthogonal directions):
```mermaid
flowchart LR
    A1[corner] --> B11[diagonal]
    A1 --> B12[!diagonal]
    A2[!corner] --> B21[diagonal]
    A2 --> B22[!diagonal]
    B11 --> single
    B21 --> single
    B12 --> corner
    B22 --> full
    B12 -.-> B11
    B22 -.-> B21
```
> single: singleton texture with connective; takes place only on corner parts; using "full" over "border center"
> corner: whether corner texture is set
> diagonal: whether diagonal tile exists
> *dotted arrow*: effect of `!side` code

**Comment by BenCheung0422** [comment]
Alright here, the conclusion is that, while both sand and grass are singleton, there is no effect with vanilla textures (as no corners) even when `!side` is removed.

**Comment by greenbean765** [comment]
thank you ben
