### ISSUE TITLE
Multiplayer compatibility issues

### ISSUE THREAD

**Issue by BenCheung0422** [MinicraftPlus/minicraft-plus-revived#712]
## Background

Originally the game was just designed to be a solo game, so many factors involved in multiplayer system have not been really considered. This is an important problem that must be solved before implementing the multiplayer system, like I have mentioned in #711.

---

The following is the list of all relevant issues and may be updated. Only the ones that can cause multiplayer balancing or behaving problems (not general issues) are tracked here.

- [ ] #693 (potential performance issue)
- [ ] #711
- [ ] Game paused on opened menus
- [ ] #508 (armor overlay)

**Comment by Makkkkus** [comment]
This issue just references some other issues and brings no new suggestions. I will therefore close this.
